@PokedexAPI_HostAddress = http://localhost:5099

GET {{PokedexAPI_HostAddress}}/api/getpokemon
Accept: application/json

###
GET https://pokeapi.co/api/v2/pokemon?limit=1000&offset=0
Accept: application/json

